# -*- coding: utf-8 -*-
"""PROJECT P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNCAGWpLoJmGVuZmcLT4_TmgN0a5YdwF

# **PHISHING URL's**
"""

import pandas as pd
data0 = pd.read_csv("/content/drive/MyDrive/ML/online-valid.csv")
data0.head()

data0.shape

phis_url = data0.sample(n = 5000, random_state = 12).copy()
phis_url = phis_url.reset_index(drop=True)
phis_url.head()

phis_url.shape

"""# **LEGITIMATE URL's**"""

data1 = pd.read_csv("/content/drive/MyDrive/ML/Benign_list_big_final.csv")
data1.columns = ['URLs']
data1.head()

legi_url = data1.sample(n = 5000, random_state = 12).copy()
legi_url = legi_url.reset_index(drop=True)
legi_url.head()

legi_url.shape

"""# **FEATURE EXTRACTION**

### **ADDRESS BAR BASED FEATURES**
"""

from urllib.parse import urlparse
from bs4 import BeautifulSoup
import ipaddress
import re
import requests

!pip install bs4

#Domain of the Url
def getDomain(url):
  domain = urlparse(url).netloc
  if re.match(r"^www.",domain):
	       domain = domain.replace("www.","")
  return domain

#checking if getDomain works
getDomain('https://www.youtube.com/results?search_query=extracting+url+information')

#IP Address in the URL
def haveIP(url):
  try:
    ipaddress.ip_address(url)
    ip = 1
  except:
    ip = 0
  return ip

#checking if haveAt works
x = '127.0.0.1'
print( haveIP(x) )
x = 'www.google.com'
print ( haveIP(x) )

#"@" Symbol in URL
def haveAt(url):
  if '@' in url:
    return 1
  else:
    return 0

#checking if haveAt works
x = 'www.google.com'
y = 'www.yahoo@gmail.com'
print( haveAt(x) )
print( haveAt(y) )

#Length of URL
def urlLength(url):
  if len(url) < 54:
    return 0
  else:
    return 1

#Depth of the URL
def getDepth(url):
  s = urlparse(url).path.split('/')
  depth = 0
  for j in range(len(s)):
    if len(s[j]) != 0:
      depth = depth+1
  return depth

#Redirection "//" in URL
def redirection(url):
  pos = url.rfind('//')
  if pos > 6:
    if pos > 7:
      return 1
    else:
      return 0
  else:
    return 0

#checking the redirection
x = 'http://eprints.hud.ac.uk/id/eprint/24330/6/MohammadPhishing14July2015.pdf'
print( redirection(x) )

#"http/https" in Domain name
def hiddenhttps(url):
  domain = urlparse(url).netloc
  print(domain)
  if 'https' in domain:
    return 1
  else:
    return 0

#checking the working of above fun
x = 'https://open.spotify.com/playlist/3mHGpdWE9oxUjcNZJvCkBe'
y = 'http://https-www-paypal-it-webapps-mpp-home.soft-hair.com/'
z = 'https://http-www-paypal-it-webapps-mpp-home.soft-hair.com/'
hiddenhttps(z)

#Using URL Shortening Services “TinyURL”
short_url_services =  r"bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|" \
                      r"yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|" \
                      r"short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|" \
                      r"doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|" \
                      r"qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|q\.gs|is\.gd|" \
                      r"po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|x\.co|" \
                      r"prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|" \
                      r"tr\.im|link\.zip\.net"

def usesTinyUrl(url):
  temp = re.search(short_url_services, url)
  if(temp):
    return 1
  else:
    return 0

#checking UsesTinyUrl fun
x = 'bit.ly/19DXSk4'
y = 'www.yahoo.com'
print( usesTinyUrl(x) )
print( usesTinyUrl(y) )

#Prefix or Suffix "-" in Domain
def haveHyphen(url):
  if '-' in urlparse(url).netloc:
    return 1
  else:
    return 0

#checking the haveHypen
print( haveHyphen('www.pay-tm.com') )
print( haveHyphen('www.google--pay-1.com'))

!pip install tldextract

#Subdomains from the URL
#checking if the Url have multi sub domain
import tldextract
def multiSubDomain(url):
  x = tldextract.extract(url)
  print(x)

#checking multi sub domain
x = 'https://www1.eposcard-co-jp-mcmbresreviec.s20r084.abc.def.ghi.cn/'
y = 'http://www.hud.ac.uk/students/page1.html'
print ( multiSubDomain(x) )
print ( multiSubDomain(y) )

#HTTP's certificate age and issuer
response = requests.get('https://stackoverflow.com/questions/29773003/check-whether-domain-is-registered')
print(response)

pip install python-whois

#Domain registration length
import whois
from datetime import datetime
from dateutil.relativedelta import relativedelta
def domainRegLength(url):
  try:
    temp = whois.whois(url)
    return relativedelta(datetime.today(), temp.creation_date[0]).years
  except:
    return 0

#checking the domdin reg len fun
x = 'www.google.com'
y = 'http://u1047531.cp.regruhosting.ru/acces-inges-20200104-t452/3facd/'
print( domainRegLength(x) )
print ( domainRegLength(y) )

"""### **DOMAIN BASED FEATURES**"""

import whois
import urllib.request
from datetime import datetime

#Web Traffic
!wget http://s3.amazonaws.com/alexa-static/top-1m.csv.zip
!unzip -o top-1m.csv.zip

'''
import urllib
import urllib.request

def web_traffic(url):
  try:
    #Filling the whitespaces in the URL if any
    url = urllib.parse.quote(url)
    rank = BeautifulSoup(urllib.request.urlopen("http://data.alexa.com/data?cli=10&dat=s&url=" + url).read(), "xml").find("REACH")['RANK']
    rank = int(rank)
  except TypeError:
        return 1
  if rank <100000:
    return 1
  else:
    return 0
'''

import csv
with open('top-1m.csv') as f:
    reader = csv.reader(f)
    alexa = list(reader)

def web_traffic(url):
  domain = getDomain(url)
  try:
    rank = [i for i, v in enumerate(alexa) if v[1] == domain][0] + 1
  except:
    return 0
  if rank <100000:
    return 1
  else:
    return 0

#Age of Domain
def domainAge(domain_name):
  creation_date = domain_name.creation_date
  expiration_date = domain_name.expiration_date
  if (isinstance(creation_date,str) or isinstance(expiration_date,str)):
    try:
      creation_date = datetime.strptime(creation_date,'%Y-%m-%d')
      expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
    except:
      return 1
  if ((expiration_date is None) or (creation_date is None)):
      return 1
  elif ((type(expiration_date) is list) or (type(creation_date) is list)):
      return 1
  else:
    ageofdomain = abs((expiration_date - creation_date).days)
    if ((ageofdomain/30) < 6):
      age = 1
    else:
      age = 0
  return age

#End Period of Domain
def domainEnd(domain_name):
  expiration_date = domain_name.expiration_date
  if isinstance(expiration_date,str):
    try:
      expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
    except:
      return 1
  if (expiration_date is None):
      return 1
  elif (type(expiration_date) is list):
      return 1
  else:
    today = datetime.now()
    end = abs((expiration_date - today).days)
    if ((end/30) < 6):
      end = 0
    else:
      end = 1
  return end

"""### **HTML & JAVASCRIPT BASED FEATURES**"""

#IFrame Redirection
def iframe(response):
    if response == "":
        return 1
    else:
        if re.findall(r"[<iframe>|<frameBorder>]", response.text):
            return 0
        else:
            return 1

#Status Bar Customization
def mouseOver(response):
  if response == "" :
    return 1
  else:
    if re.findall("<script>.+onmouseover.+</script>", response.text):
      return 1
    else:
      return 0

#Disabling Right Click
def rightClick(response):
  if response == "":
    return 1
  else:
    if re.findall(r"event.button ?== ?2", response.text):
      return 0
    else:
      return 1

#Website Forwarding
def forwarding(response):
  if response == "":
    return 1
  else:
    if len(response.history) <= 2:
      return 0
    else:
      return 1

"""# **COMPUTING URL FEATURES**"""

def featureExtraction(url,label, curr):
  feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection',
                      'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record',
                      'Domain_Age', 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 'Label']
  features = []
  #Address bar based features  are working correctly
  features.append(getDomain(url))
  features.append(haveIP(url))
  features.append(haveAt(url))
  features.append(urlLength(url))
  features.append(getDepth(url))
  features.append(redirection(url))
  features.append(hiddenhttps(url))
  features.append(usesTinyUrl(url))
  features.append(haveHyphen(url))

  #Domain based features  working correctly
  dns = 0
  try:
    domain_name = whois.whois(urlparse(url).netloc)
  except:
    dns = 1

  features.append(dns)
  features.append(web_traffic(url))
  features.append(1 if dns == 1 else domainAge(domain_name))
  features.append(1 if dns == 1 else domainEnd(domain_name))

  # HTML & Javascript based features working correctly
  temp = ['1']*4
  temp.append(label)

  try:
    response = requests.get(url, timeout=5 )
    print('HTTP response code: ', response.status_code)
    if response.status_code == 200:
      features.append(iframe(response))
      features.append(mouseOver(response))
      features.append(rightClick(response))
      features.append(forwarding(response))
      features.append(label)
    else:
      print('Not reachable - ', url)
      features.extend(temp)
  except:
    print('Timeout - ', url)
    features.extend(temp)


  return features

"""### **LEGITIMATE URL's**"""

#Extracting the feautres & storing them in a list
legi_features = []
label = 0
for i in range(0, 5000):
  url = legi_url['URLs'][i]
  print('i is: ', i, 'url: ', legi_url['URLs'][i]  )
  legi_features.append(featureExtraction(url,label,i))

from numpy import array
x = array(legi_features)
print(x.shape)

x[15]

feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection',
                      'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Web_Traffic',
                      'Domain_Age', 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 'Label']

legitimate = pd.DataFrame(legi_features, columns= feature_names)
legitimate.head()

legitimate.to_csv('legitimate.csv', index= False)

"""### **PHISHING URL's**"""

phis_url.shape

#Extracting the feautres & storing them in a list
phish_features = []
label = 1
for i in range(0, 5000):
  url = phis_url['url'][i]
  print('i is: ', i, 'url: ', legi_url['URLs'][i]  )
  phish_features.append(featureExtraction(url,label, i))

#converting the list to dataframe
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection',
                      'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Web_Traffic',
                      'Domain_Age', 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 'Label']
phishing = pd.DataFrame(phish_features, columns= feature_names)
phishing.head()

phishing.to_csv('phishing.csv', index= False)

"""# **FINAL DATASET**"""

urldata = pd.concat([legitimate, phishing]).reset_index(drop=True)
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection',
                      'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Web_Traffic',
                      'Domain_Age', 'Domain_End', 'iFrame', 'Mouse_Over','Right_Click', 'Web_Forwards', 'Label']
urldata = pd.DataFrame(urldata, columns= feature_names)
urldata.head()

urldata.tail()

urldata.shape

urldata.to_csv('urldata.csv', index=False)